<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>GeometryEncoder.ToCurve Method (LineCurve)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:RhinoInside.Revit.Convert.Geometry.GeometryEncoder.ToCurve(Rhino.Geometry.LineCurve)" /><meta name="Description" content="Converts the specified to an equivalent of ." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="RhinoInside.Revit.Convert.Geometry" /><meta name="file" content="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_4" /><meta name="guid" content="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_4" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.5.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoInside.Revit API Documentation<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoInside_Revit_API.htm" title="RhinoInside.Revit API Documentation" tocid="roottoc">RhinoInside.Revit API Documentation</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoInside_Revit_API.htm" title="Namespaces" tocid="R_Project_RhinoInside_Revit_API">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_RhinoInside_Revit_Convert_Geometry.htm" title="RhinoInside.Revit.Convert.Geometry" tocid="N_RhinoInside_Revit_Convert_Geometry">RhinoInside.Revit.Convert.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_RhinoInside_Revit_Convert_Geometry_GeometryEncoder.htm" title="GeometryEncoder Class" tocid="T_RhinoInside_Revit_Convert_Geometry_GeometryEncoder">GeometryEncoder Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_RhinoInside_Revit_Convert_Geometry_GeometryEncoder.htm" title="GeometryEncoder Methods" tocid="Methods_T_RhinoInside_Revit_Convert_Geometry_GeometryEncoder">GeometryEncoder Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve.htm" title="ToCurve Method " tocid="Overload_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve">ToCurve Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve.htm" title="ToCurve Method (ArcCurve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve">ToCurve Method (ArcCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_1.htm" title="ToCurve Method (Curve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_1">ToCurve Method (Curve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_2.htm" title="ToCurve Method (Ellipse)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_2">ToCurve Method (Ellipse)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_4.htm" title="ToCurve Method (LineCurve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_4">ToCurve Method (LineCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_5.htm" title="ToCurve Method (NurbsCurve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_5">ToCurve Method (NurbsCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_6.htm" title="ToCurve Method (PolyCurve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_6">ToCurve Method (PolyCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_7.htm" title="ToCurve Method (PolylineCurve)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_7">ToCurve Method (PolylineCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_3.htm" title="ToCurve Method (Ellipse, Interval)" tocid="M_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve_3">ToCurve Method (Ellipse, Interval)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>GeometryEncoder<span id="LSTFA28CF48_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFA28CF48_0?cpp=::|nu=.");</script>ToCurve Method (LineCurve)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
             Converts the specified <a href="https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_LineCurve.htm" target="_blank" rel="noopener noreferrer">Rhino.Geometry.LineCurve</a> to an equivalent of <a href="https://api.apidocs.co/resolve/revit/2020/?asset_id=T:Autodesk.Revit.DB.Curve" target="_blank" rel="noopener noreferrer">Autodesk.Revit.DB.Curve</a>.
             </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_RhinoInside_Revit_Convert_Geometry.htm">RhinoInside.Revit.Convert.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoInside.Revit (in RhinoInside.Revit.dll) Version: 1.5.8026<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','py','2','2');return false;">Python</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <a href="https://api.apidocs.co/resolve/revit/2020/?asset_id=T:Autodesk.Revit.DB.Curve" target="_blank" rel="noopener noreferrer">Autodesk.Revit.DB.Curve</a> <span class="identifier">ToCurve</span>(
	<span class="keyword">this</span> <a href="https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_LineCurve.htm" target="_blank" rel="noopener noreferrer">Rhino.Geometry.LineCurve</a> <span class="parameter">lineCurve</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">@staticmethod</span>
<span class="keyword">def</span> <span class="identifier">ToCurve</span>(
	<span class="parameter">lineCurve</span>: <a href="https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_LineCurve.htm" target="_blank" rel="noopener noreferrer">Rhino.Geometry.LineCurve</a>
) -&gt; <a href="https://api.apidocs.co/resolve/revit/2020/?asset_id=T:Autodesk.Revit.DB.Curve" target="_blank" rel="noopener noreferrer">Autodesk.Revit.DB.Curve</a></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">lineCurve</span></dt><dd>Type: <a href="https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_LineCurve.htm" target="_blank" rel="noopener noreferrer">Rhino.Geometry.LineCurve</a><br />Rhino lineCurve to convert.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="https://api.apidocs.co/resolve/revit/2020/?asset_id=T:Autodesk.Revit.DB.Curve" target="_blank" rel="noopener noreferrer">Autodesk.Revit.DB.Curve</a><br />Revit curve that is equivalent to the provided Rhino lineCurve.<h4 class="subHeading">Usage Note</h4>In Visual Basic and C#, you can call this method as an instance method on any object of type <a href="https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_LineCurve.htm" target="_blank" rel="noopener noreferrer">Rhino.Geometry.LineCurve</a>. When you use instance method syntax to call this method, omit the first parameter. For more information, see <a href="https://docs.microsoft.com/dotnet/visual-basic/programming-guide/language-features/procedures/extension-methods" target="_blank" rel="noopener noreferrer">Extension Methods (Visual Basic)</a> or <a href="https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/extension-methods" target="_blank" rel="noopener noreferrer">Extension Methods (C# Programming Guide)</a>.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection">
             
             Using <span class="selflink">ToCurve(LineCurve)</span> as extension method:
            
             <div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBECBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBECBA','cs','1','2');return false;">C#</a></div><div id="ID0EBECBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBECBA','py','2','2');return false;">Python</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBECBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBECBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBECBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-spacerShort"></span><span class="highlight-keyword">using</span> DB = Autodesk.Revit.DB;
<span class="highlight-spacerShort"></span><span class="highlight-keyword">using</span> RhinoInside.Revit.Convert.Geometry;
<span class="highlight-spacerShort"></span>
<span class="highlight-spacerShort"></span>DB.Curve revitCurve = rhinoLineCurve.ToCurve();</pre></div><div id="ID0EBECBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> clr
<span class="highlight-spacerShort"></span>clr.AddReference(<span class="highlight-literal">"RevitAPI"</span>)
<span class="highlight-spacerShort"></span>clr.AddReference(<span class="highlight-literal">"RhinoInside.Revit"</span>)
<span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> Autodesk.Revit.DB <span class="highlight-keyword">as</span> DB
<span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> RhinoInside.Revit.Convert.Geometry
<span class="highlight-spacerShort"></span>clr.ImportExtensions(RhinoInside.Revit.Convert.Geometry)
<span class="highlight-spacerShort"></span>
<span class="highlight-spacerShort"></span>revit_curve = rhino_linecurve.ToCurve()    <span class="highlight-comment"># type: DB.Curve</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBECBA");</script>
             
             Using <span class="selflink">ToCurve(LineCurve)</span> as static method:
            
             <div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBACBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBACBA','cs','1','2');return false;">C#</a></div><div id="ID0EBACBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBACBA','py','2','2');return false;">Python</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBACBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBACBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBACBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-spacerShort"></span><span class="highlight-keyword">using</span> DB = Autodesk.Revit.DB;
<span class="highlight-spacerShort"></span><span class="highlight-keyword">using</span> RhinoInside.Revit.Convert.Geometry;
<span class="highlight-spacerShort"></span>
<span class="highlight-spacerShort"></span>DB.Curve revitCurve = GeometryEncoder.ToCurve(rhinoLineCurve);</pre></div><div id="ID0EBACBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> clr
<span class="highlight-spacerShort"></span>clr.AddReference(<span class="highlight-literal">"RevitAPI"</span>)
<span class="highlight-spacerShort"></span>clr.AddReference(<span class="highlight-literal">"RhinoInside.Revit"</span>)
<span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> Autodesk.Revit.DB <span class="highlight-keyword">as</span> DB
<span class="highlight-spacerShort"></span><span class="highlight-keyword">import</span> RhinoInside.Revit.Convert.Geometry.GeometryEncoder <span class="highlight-keyword">as</span> GE
<span class="highlight-spacerShort"></span>
<span class="highlight-spacerShort"></span>revit_curve = GE.ToCurve(rhino_linecurve)    <span class="highlight-comment"># type: DB.Curve</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBACBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_RhinoInside_Revit_Convert_Geometry_GeometryEncoder.htm">GeometryEncoder Class</a></div><div class="seeAlsoStyle"><a href="Overload_RhinoInside_Revit_Convert_Geometry_GeometryEncoder_ToCurve.htm">ToCurve Overload</a></div><div class="seeAlsoStyle"><a href="N_RhinoInside_Revit_Convert_Geometry.htm">RhinoInside.Revit.Convert.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter"><p><a href="https://discourse.mcneel.com/c/rhino-inside/Revit" target="_blank" rel="noopener noreferrer">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>